x265: fix build on x86_64-darwin
Update to 3.6 pulled in local definition of `__rdtsc()` symbol in
the test suite and caused symbol clash:

    /tmp/nix-build-x265-3.6.drv-0/x265_3.6/source/test/testharness.h:78:24: error: static declaration of '__rdtsc' follows non-static declaration
    static inline uint32_t __rdtsc(void)
                           ^
    /tmp/nix-build-x265-3.6.drv-0/x265_3.6/source/test/testharness.h:78:24: note: '__rdtsc' is a builtin with type 2

The change avoids redefinition if the compiler already provides the
builtin.