perlInterpreters.perl536: drop the attribute
Without the change `nixpkgs` exposes unevaluatable attribute as:

    $ nix build --no-link -f. perlInterpreters.perl536.perlOnBuild
    error: attribute 'perl536' missing
       at pkgs/development/interpreters/perl/interpreter.nix:207:37:
          206|       perlOnBuildForBuild = override pkgsBuildBuild.${perlAttr};
          207|       perlOnBuildForHost = override pkgsBuildHost.${perlAttr};
             |                                     ^
          208|       perlOnBuildForTarget = override pkgsBuildTarget.${perlAttr};
       Did you mean one of perl538 or perl540?

The interpreter depends on presence of `perl536` attribute which wa
removed recently.