hpp-fcl: add missing dependency
fix:
```python
>>> import hppfcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/dfnl1p604453r5rc29h3bnr4vjn811lj-hpp-fcl-3.0.0-pre/lib/python3.11/site-packages/hppfcl/__init__.py", line 35, in <module>
    from .hppfcl import *
ImportError: libz.so.1: cannot open shared object file: No such file or directory
```