power-profiles-daemon: Fix missing typelib
gobject-instrospection before version 1.80 shipped typelibs for GLib.
As a result, programs relying on libgirepository such as those using pygobject3
would find the GLib typelibs without being wrapped at all.

In GNOME 46, the GLib typelibs were moved to glib package. So if we want
a program to find them, they need to be explicitly passed through `GI_TYPELIB_PATH`
environment variable.

This can be demonstrated by running `GI_TYPELIB_PATH= powerprofilesctl`:

    ImportError: cannot import name Gio, introspection typelib not found

Let’s add the library to path using a wrapper.