pdfslicer: work around incompatibility with GCC 13
GCC 13 introduced warning `-Wchanges-meaning`, resulting in build failure:

    /build/source/third-party/range-v3/include/meta/meta.hpp:3165:19: error: declaration of 'template<class Fn> template<class State, class A> using meta::detail::partition_<Fn>::invoke = meta::_t<meta::detail::partition_<Fn>::impl<State, A> >' changes meaning of 'invoke' [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wchanges-meaning-Wchanges-meaning8;;]
     3165 |             using invoke = _t<impl<State, A>>;
          |                   ^~~~~~
    /build/source/third-party/range-v3/include/meta/meta.hpp:3160:34: note: used here to mean 'using meta::invoke = typename Fn::invoke<A>'
     3160 |                 using type = if_<invoke<Fn, A>, pair<list<Yes..., A>, list<No...>>,
          |                                  ^~~~~~~~~~~~~
    /build/source/third-party/range-v3/include/meta/meta.hpp:541:11: note: declared here
      541 |     using invoke = typename Fn::template invoke<Args...>;
          |           ^~~~~~

Upstream appears to be unmaintained, so for now just disable the warning.