waybar: fix `gcc-14` build by syncing `cava` version
Without the change the build against `gcc-14` fails as:

    $ nix build --impure --expr 'with import ./. {}; waybar.override {stdenv = gcc14Stdenv; }' -L
    ...
    ../subprojects/cava-0.10.1/src/config.c: In function 'load_config':
    ../subprojects/cava-0.10.1/src/config.c:412:24: error: implicit declaration of function 'getenv' [-Wimplicit-function-declaration]
      412 |     char *configHome = getenv("XDG_CONFIG_HOME");
          |                        ^~~~~~

It was fixed upstream in 0.10.2. The change updates to it.