postgresqlPackages.promscale_extension: remove deprecated and broken package
postgresql14Packages.promscale_extension breaks with:

  Error:
    0: `pgx-0.6.1` shouldn't be used with `cargo-pgx-0.7.4`,
    please use `pgx = "~0.7.4"` in your `Cargo.toml`.

However, pinning cargo-pgx to 0_6_1 via the following

  buildPgxExtension.override { cargo-pgx = cargo-pgx_0_6_1; }

does not work either, because the build then fails with:

  thread 'main' panicked at /build/promscale_extension-0.8.0-vendor.tar.gz/proc-macro2/src/fallback.rs:756:9:
  "__mbstate_t_union_(unnamed_at_/nix/store/ij144ma6vs8acil8r9hgr8xkb1dp9azg-glibc-2_39-5-dev/include/bits/types/__mbstate_t_h_16_3)" is not a valid Ident

This seems to be related to [1], which indicates that this is a
problem with newer LLVM / clang toolchains.

At the same time th upstream package is deprecated / archived since
the 2nd of April 2024 [2]. Additionally this package is unfree and
thus very unlikely to be forked. Since we can't expect this to be
fixed, the only sensible thing to do is to remove the package.

[1]: https://github.com/rust-lang/rust-bindgen/issues/2312
[2]: https://github.com/timescale/promscale/issues/1836