texpresso/tectonic: Fix cargoHash (#334797)
Hash mismatch was caused by #333143.

The build error message contains:

    Validating consistency between /build/source/Cargo.lock and /build/texpresso-tonic-0.15.0-vendor.tar.gz/Cargo.lock
    2372d2371
    <  "time",
    2707c2706
    < version = "0.3.36"
    ---
    > version = "0.3.34"
    ...
    ERROR: cargoHash or cargoSha256 is out of date

Fixes #334648.