chromium: fix building M125 with ninja 1.12
Solves the following build error:

~~~
FAILED: obj/chrome/browser/devtools/devtools/devtools_window.o
In file included from ../../chrome/browser/devtools/devtools_window.cc:32:
../../chrome/browser/file_select_helper.h:16:10: fatal error: 'components/enterprise/buildflags/buildflags.h' file not found
 16 | #include "components/enterprise/buildflags/buildflags.h"
    |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~

Can be removed once chromium and ungoogled-chromium are both on M126,
since the patch is from M126.

https://issues.chromium.org/issues/336911498
https://chromium-review.googlesource.com/c/chromium/src/+/5487538