libdevil: fix compilation on Darwin with clang
Compilation fails now that the default C++ standard is 17, because the
(rather old) upstream code uses the "register" keyword.

./../src-IL/include/il_manip.h:63:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int m =   i        & 0x007fffff;
        ^~~~~~~~~

We could selectively set -std=c++14, but it also seems sufficient to
suppress the warning, so this commit chooses that option.