pcre2: backport jit auto-detection
Without the change `pcre2` build without `jit` support. This happens
because --wit-jit=auto was broken in this release. THe change backports
upstream fix.

Before the change ./configure log:

    pcre2>     Enable JIT compiling support ....... : no

After the change:

    pcre2>     Enable JIT compiling support ....... : yes

I initially observed the failures on `rizin` as a spam of failures to
JIT a trivial regex:

    $ rizin
    ERROR: Regex compilation for '\s+' failed at 0: bad JIT option
    ERROR: Regex compilation for '\s+' failed at 0: bad JIT option
    ...
    ERROR: Regex compilation for '\s+' failed at 0: bad JIT option
     -- Check your IO plugins with 'rizin -L'
    [0x00000000]>