pretix: pin django-oauth-toolkit at 2.3.0
Pretix is not yet compatible with newer releases, and it shows when
visiting `/control/settings/history`, which ends in a trace with a db
field that was introduced in 2.4.0:

> django.db.utils.ProgrammingError: column pretixapi_oauthapplication.hash_client_secret does not exist