tests.dotnet.project-references: use dir instead of file output
This fixes an error in nixpkgs-review when it tries to pass this to
buildEnv:

error: The store path [...]project-references-test is a file and can't
be merged into an environment using pkgs.buildEnv! at [...]-builder.pl
line 122.