common-updater-scripts: Fix u-s-v updating npmDeps
`buildNpmDeps` pass `npmDepsHash` as `hash` to `fetchNpmDeps` so `npmDeps` does not contain `outputHashAlgo` attribute.

This would cause the program fail as follows:

    $ update-source-version zx --ignore-same-version --source-key=npmDeps
    error: attribute 'outputHashAlgo' in selection path 'zx.npmDeps.drvAttrs.outputHashAlgo' not found
    update-source-version: error: Couldn't evaluate old source hash from 'zx.npmDeps'!